export interface StrategicCity {
  id: string;
  name: string;
  country: string;
  countryCode: string;
  flagUrl: string;
  lat: number;
  lng: number;
  population: string;
  economicOutput: string; // GDP/Economic Value
  militaryReadiness: string;
  defenseStatus: 'Fortified' | 'Active' | 'Defended';
  description: string;
}

export const STRATEGIC_CITIES: StrategicCity[] = [
  {
    id: 'city-newyork',
    name: 'New York City',
    country: 'United States',
    countryCode: 'US',
    flagUrl: 'https://flagcdn.com/w80/us.png',
    lat: 40.7128,
    lng: -74.006,
    population: '8.8 Million',
    economicOutput: '$2.1 Trillion',
    militaryReadiness: 'DEFCON 3',
    defenseStatus: 'Fortified',
    description: 'Global financial capital, home to Wall Street and United Nations Headquarters.',
  },
  {
    id: 'city-tokyo',
    name: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    flagUrl: 'https://flagcdn.com/w80/jp.png',
    lat: 35.6762,
    lng: 139.6503,
    population: '14.0 Million',
    economicOutput: '$2.0 Trillion',
    militaryReadiness: 'Air Defense Tier 1',
    defenseStatus: 'Fortified',
    description: 'Metropolitan economic giant and high-technology manufacturing command.',
  },
  {
    id: 'city-london',
    name: 'London',
    country: 'United Kingdom',
    countryCode: 'GB',
    flagUrl: 'https://flagcdn.com/w80/gb.png',
    lat: 51.5074,
    lng: -0.1278,
    population: '9.0 Million',
    economicOutput: '$980 Billion',
    militaryReadiness: 'QRA Ready',
    defenseStatus: 'Defended',
    description: 'Sovereign financial heart and Whitehall strategic military administration.',
  },
  {
    id: 'city-paris',
    name: 'Paris',
    country: 'France',
    countryCode: 'FR',
    flagUrl: 'https://flagcdn.com/w80/fr.png',
    lat: 48.8566,
    lng: 2.3522,
    population: '2.1 Million (11M Metro)',
    economicOutput: '$890 Billion',
    militaryReadiness: 'Hexagone Alert',
    defenseStatus: 'Fortified',
    description: 'Diplomatic hub and European aerospace industrial nexus.',
  },
  {
    id: 'city-beijing',
    name: 'Beijing',
    country: 'China',
    countryCode: 'CN',
    flagUrl: 'https://flagcdn.com/w80/cn.png',
    lat: 39.9042,
    lng: 116.4074,
    population: '21.5 Million',
    economicOutput: '$1.7 Trillion',
    militaryReadiness: 'Ring Defense Grid',
    defenseStatus: 'Fortified',
    description: 'Sovereign political center and Central Military Commission command citadel.',
  },
  {
    id: 'city-abuja',
    name: 'Abuja',
    country: 'Nigeria',
    countryCode: 'NG',
    flagUrl: 'https://flagcdn.com/w80/ng.png',
    lat: 9.0765,
    lng: 7.3986,
    population: '3.8 Million',
    economicOutput: '$140 Billion',
    militaryReadiness: 'Sector HQ Guard',
    defenseStatus: 'Active',
    description: 'Federal capital nexus and Defence Headquarters strategic coordination center.',
  },
  {
    id: 'city-cairo',
    name: 'Cairo',
    country: 'Egypt',
    countryCode: 'EG',
    flagUrl: 'https://flagcdn.com/w80/eg.png',
    lat: 30.0444,
    lng: 31.2357,
    population: '22.0 Million',
    economicOutput: '$220 Billion',
    militaryReadiness: 'Suez Gateway Ready',
    defenseStatus: 'Defended',
    description: 'Historic gateway commanding Suez maritime transit corridors and Nile basin.',
  },
  {
    id: 'city-berlin',
    name: 'Berlin',
    country: 'Germany',
    countryCode: 'DE',
    flagUrl: 'https://flagcdn.com/w80/de.png',
    lat: 52.52,
    lng: 13.405,
    population: '3.7 Million',
    economicOutput: '$260 Billion',
    militaryReadiness: 'Central Shield Sync',
    defenseStatus: 'Active',
    description: 'European powerhouse political center and critical continental transport hub.',
  },
  {
    id: 'city-newdelhi',
    name: 'New Delhi',
    country: 'India',
    countryCode: 'IN',
    flagUrl: 'https://flagcdn.com/w80/in.png',
    lat: 28.6139,
    lng: 77.209,
    population: '33.0 Million',
    economicOutput: '$520 Billion',
    militaryReadiness: 'Tri-Service Command',
    defenseStatus: 'Fortified',
    description: 'South Asian sovereign nerve center and integrated defense staff headquarters.',
  },
  {
    id: 'city-seoul',
    name: 'Seoul',
    country: 'South Korea',
    countryCode: 'KR',
    flagUrl: 'https://flagcdn.com/w80/kr.png',
    lat: 37.5665,
    lng: 126.978,
    population: '9.7 Million',
    economicOutput: '$950 Billion',
    militaryReadiness: 'Iron Shield Continuous',
    defenseStatus: 'Fortified',
    description: 'Advanced technological capital guarded by high-density subterranean defenses.',
  },
  {
    id: 'city-moscow',
    name: 'Moscow',
    country: 'Russia',
    countryCode: 'RU',
    flagUrl: 'https://flagcdn.com/w80/ru.png',
    lat: 55.7558,
    lng: 37.6173,
    population: '13.1 Million',
    economicOutput: '$820 Billion',
    militaryReadiness: 'Kremlin Ring Sentinel',
    defenseStatus: 'Fortified',
    description: 'Eurasian administrative citadel and national defense management center.',
  },
  {
    id: 'city-riyadh',
    name: 'Riyadh',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    flagUrl: 'https://flagcdn.com/w80/sa.png',
    lat: 24.7136,
    lng: 46.6753,
    population: '7.6 Million',
    economicOutput: '$410 Billion',
    militaryReadiness: 'Patriot Net Active',
    defenseStatus: 'Defended',
    description: 'Gulf financial fortress and strategic petroleum economic headquarters.',
  },
];
