export interface StrategicCity {
  id: string;
  name: string;
  country: string;
  countryCode: string;
  flagUrl: string;
  lat: number;
  lng: number;
  population: string;
  economicOutput: string; // GDP/Economic Value
  militaryReadiness: string;
  defenseStatus: 'Fortified' | 'Active' | 'Defended';
  description: string;
  isOccupied?: boolean;
  occupyingCountry?: string; // country code
  occupyingCountryName?: string;
  garrisonStrength?: string;
}

export const STRATEGIC_CITIES: StrategicCity[] = [
  // United States
  {
    id: 'city-newyork',
    name: 'New York City',
    country: 'United States',
    countryCode: 'US',
    flagUrl: 'https://flagcdn.com/w80/us.png',
    lat: 40.7128,
    lng: -74.006,
    population: '8.8 Million',
    economicOutput: '$2.1 Trillion',
    militaryReadiness: 'DEFCON 3',
    defenseStatus: 'Fortified',
    description: 'Global financial capital, home to Wall Street and United Nations Headquarters.',
  },
  {
    id: 'city-washington',
    name: 'Washington, D.C.',
    country: 'United States',
    countryCode: 'US',
    flagUrl: 'https://flagcdn.com/w80/us.png',
    lat: 38.9072,
    lng: -77.0369,
    population: '710,000 (6.3M Metro)',
    economicOutput: '$620 Billion',
    militaryReadiness: 'DEFCON 2',
    defenseStatus: 'Fortified',
    description: 'Federal capital nexus, Pentagon command headquarters, and National Military Command Center.',
  },
  {
    id: 'city-losangeles',
    name: 'Los Angeles',
    country: 'United States',
    countryCode: 'US',
    flagUrl: 'https://flagcdn.com/w80/us.png',
    lat: 34.0522,
    lng: -118.2437,
    population: '3.9 Million (10M Metro)',
    economicOutput: '$1.1 Trillion',
    militaryReadiness: 'Pacific Shield',
    defenseStatus: 'Defended',
    description: 'Pacific maritime gateway, aerospace engineering hub, and commercial container terminal.',
  },
  {
    id: 'city-chicago',
    name: 'Chicago',
    country: 'United States',
    countryCode: 'US',
    flagUrl: 'https://flagcdn.com/w80/us.png',
    lat: 41.8781,
    lng: -87.6298,
    population: '2.7 Million',
    economicOutput: '$750 Billion',
    militaryReadiness: 'Midwest Grid Guard',
    defenseStatus: 'Active',
    description: 'Central continental logistics artery, commodity trading citadel, and industrial transport hub.',
  },

  // United Kingdom
  {
    id: 'city-london',
    name: 'London',
    country: 'United Kingdom',
    countryCode: 'GB',
    flagUrl: 'https://flagcdn.com/w80/gb.png',
    lat: 51.5074,
    lng: -0.1278,
    population: '9.0 Million',
    economicOutput: '$980 Billion',
    militaryReadiness: 'QRA Ready',
    defenseStatus: 'Defended',
    description: 'Sovereign financial heart and Whitehall strategic military administration.',
  },
  {
    id: 'city-manchester',
    name: 'Manchester',
    country: 'United Kingdom',
    countryCode: 'GB',
    flagUrl: 'https://flagcdn.com/w80/gb.png',
    lat: 53.4808,
    lng: -2.2426,
    population: '2.8 Million Metro',
    economicOutput: '$110 Billion',
    militaryReadiness: 'Northern Shield',
    defenseStatus: 'Active',
    description: 'Industrial tech nucleus and strategic northern defense production network.',
  },

  // France
  {
    id: 'city-paris',
    name: 'Paris',
    country: 'France',
    countryCode: 'FR',
    flagUrl: 'https://flagcdn.com/w80/fr.png',
    lat: 48.8566,
    lng: 2.3522,
    population: '2.1 Million (11M Metro)',
    economicOutput: '$890 Billion',
    militaryReadiness: 'Hexagone Alert',
    defenseStatus: 'Fortified',
    description: 'Diplomatic hub and European aerospace industrial nexus.',
  },
  {
    id: 'city-marseille',
    name: 'Marseille',
    country: 'France',
    countryCode: 'FR',
    flagUrl: 'https://flagcdn.com/w80/fr.png',
    lat: 43.2965,
    lng: 5.3698,
    population: '870,000 (1.8M Metro)',
    economicOutput: '$95 Billion',
    militaryReadiness: 'Mediterranean Fleet Ready',
    defenseStatus: 'Defended',
    description: 'Primary Mediterranean maritime terminal and strategic naval replenishment bastion.',
  },

  // Germany
  {
    id: 'city-berlin',
    name: 'Berlin',
    country: 'Germany',
    countryCode: 'DE',
    flagUrl: 'https://flagcdn.com/w80/de.png',
    lat: 52.52,
    lng: 13.405,
    population: '3.7 Million',
    economicOutput: '$260 Billion',
    militaryReadiness: 'Central Shield Sync',
    defenseStatus: 'Active',
    description: 'European powerhouse political center and critical continental transport hub.',
  },
  {
    id: 'city-munich',
    name: 'Munich',
    country: 'Germany',
    countryCode: 'DE',
    flagUrl: 'https://flagcdn.com/w80/de.png',
    lat: 48.1351,
    lng: 11.582,
    population: '1.5 Million',
    economicOutput: '$240 Billion',
    militaryReadiness: 'Southern Command Grid',
    defenseStatus: 'Fortified',
    description: 'Bavarian advanced engineering capital and defense electronics fabrication stronghold.',
  },

  // Japan
  {
    id: 'city-tokyo',
    name: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    flagUrl: 'https://flagcdn.com/w80/jp.png',
    lat: 35.6762,
    lng: 139.6503,
    population: '14.0 Million (37M Metro)',
    economicOutput: '$2.0 Trillion',
    militaryReadiness: 'Air Defense Tier 1',
    defenseStatus: 'Fortified',
    description: 'Metropolitan economic giant and high-technology manufacturing command.',
  },
  {
    id: 'city-osaka',
    name: 'Osaka',
    country: 'Japan',
    countryCode: 'JP',
    flagUrl: 'https://flagcdn.com/w80/jp.png',
    lat: 34.6937,
    lng: 135.5023,
    population: '2.7 Million (19M Metro)',
    economicOutput: '$780 Billion',
    militaryReadiness: 'Kansai Defense Net',
    defenseStatus: 'Defended',
    description: 'Kansai industrial powerhouse and robotics heavy manufacturing node.',
  },

  // China
  {
    id: 'city-beijing',
    name: 'Beijing',
    country: 'China',
    countryCode: 'CN',
    flagUrl: 'https://flagcdn.com/w80/cn.png',
    lat: 39.9042,
    lng: 116.4074,
    population: '21.5 Million',
    economicOutput: '$1.7 Trillion',
    militaryReadiness: 'Ring Defense Grid',
    defenseStatus: 'Fortified',
    description: 'Sovereign political center and Central Military Commission command citadel.',
  },
  {
    id: 'city-shanghai',
    name: 'Shanghai',
    country: 'China',
    countryCode: 'CN',
    flagUrl: 'https://flagcdn.com/w80/cn.png',
    lat: 31.2304,
    lng: 121.4737,
    population: '28.5 Million',
    economicOutput: '$2.4 Trillion',
    militaryReadiness: 'Eastern Theater Command',
    defenseStatus: 'Fortified',
    description: 'Busiest container port on Earth and sovereign commercial financial citadel.',
  },

  // Russia
  {
    id: 'city-moscow',
    name: 'Moscow',
    country: 'Russia',
    countryCode: 'RU',
    flagUrl: 'https://flagcdn.com/w80/ru.png',
    lat: 55.7558,
    lng: 37.6173,
    population: '13.1 Million',
    economicOutput: '$820 Billion',
    militaryReadiness: 'Kremlin Ring Sentinel',
    defenseStatus: 'Fortified',
    description: 'Eurasian administrative citadel and national defense management center.',
  },
  {
    id: 'city-stpetersburg',
    name: 'Saint Petersburg',
    country: 'Russia',
    countryCode: 'RU',
    flagUrl: 'https://flagcdn.com/w80/ru.png',
    lat: 59.9343,
    lng: 30.3351,
    population: '5.6 Million',
    economicOutput: '$290 Billion',
    militaryReadiness: 'Baltic Fleet Bastion',
    defenseStatus: 'Defended',
    description: 'Baltic gateway, naval shipbuilding admiralty, and strategic maritime bastion.',
  },

  // India
  {
    id: 'city-newdelhi',
    name: 'New Delhi',
    country: 'India',
    countryCode: 'IN',
    flagUrl: 'https://flagcdn.com/w80/in.png',
    lat: 28.6139,
    lng: 77.209,
    population: '33.0 Million',
    economicOutput: '$520 Billion',
    militaryReadiness: 'Tri-Service Command',
    defenseStatus: 'Fortified',
    description: 'South Asian sovereign nerve center and integrated defense staff headquarters.',
  },
  {
    id: 'city-mumbai',
    name: 'Mumbai',
    country: 'India',
    countryCode: 'IN',
    flagUrl: 'https://flagcdn.com/w80/in.png',
    lat: 19.076,
    lng: 72.8777,
    population: '21.0 Million',
    economicOutput: '$610 Billion',
    militaryReadiness: 'Western Naval Command',
    defenseStatus: 'Fortified',
    description: 'Financial capital of India and strategic Arabian Sea naval operational command.',
  },

  // Nigeria
  {
    id: 'city-abuja',
    name: 'Abuja',
    country: 'Nigeria',
    countryCode: 'NG',
    flagUrl: 'https://flagcdn.com/w80/ng.png',
    lat: 9.0765,
    lng: 7.3986,
    population: '3.8 Million',
    economicOutput: '$140 Billion',
    militaryReadiness: 'Sector HQ Guard',
    defenseStatus: 'Active',
    description: 'Federal capital nexus and Defence Headquarters strategic coordination center.',
  },
  {
    id: 'city-lagos',
    name: 'Lagos',
    country: 'Nigeria',
    countryCode: 'NG',
    flagUrl: 'https://flagcdn.com/w80/ng.png',
    lat: 6.5244,
    lng: 3.3792,
    population: '16.0 Million (24M Metro)',
    economicOutput: '$180 Billion',
    militaryReadiness: 'Atlantic Coastal Watch',
    defenseStatus: 'Fortified',
    description: 'Sub-Saharan Africa commercial mega-hub, tech capital, and maritime trade terminus.',
  },

  // Egypt
  {
    id: 'city-cairo',
    name: 'Cairo',
    country: 'Egypt',
    countryCode: 'EG',
    flagUrl: 'https://flagcdn.com/w80/eg.png',
    lat: 30.0444,
    lng: 31.2357,
    population: '22.0 Million',
    economicOutput: '$220 Billion',
    militaryReadiness: 'Suez Gateway Ready',
    defenseStatus: 'Defended',
    description: 'Historic gateway commanding Suez maritime transit corridors and Nile basin.',
  },

  // Saudi Arabia
  {
    id: 'city-riyadh',
    name: 'Riyadh',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    flagUrl: 'https://flagcdn.com/w80/sa.png',
    lat: 24.7136,
    lng: 46.6753,
    population: '7.6 Million',
    economicOutput: '$410 Billion',
    militaryReadiness: 'Patriot Net Active',
    defenseStatus: 'Defended',
    description: 'Gulf financial fortress and strategic petroleum economic headquarters.',
  },

  // South Korea
  {
    id: 'city-seoul',
    name: 'Seoul',
    country: 'South Korea',
    countryCode: 'KR',
    flagUrl: 'https://flagcdn.com/w80/kr.png',
    lat: 37.5665,
    lng: 126.978,
    population: '9.7 Million',
    economicOutput: '$950 Billion',
    militaryReadiness: 'Iron Shield Continuous',
    defenseStatus: 'Fortified',
    description: 'Advanced technological capital guarded by high-density subterranean defenses.',
  },

  // Brazil
  {
    id: 'city-brasilia',
    name: 'Brasilia',
    country: 'Brazil',
    countryCode: 'BR',
    flagUrl: 'https://flagcdn.com/w80/br.png',
    lat: -15.7975,
    lng: -47.8919,
    population: '3.1 Million',
    economicOutput: '$130 Billion',
    militaryReadiness: 'Planalto Defense Grid',
    defenseStatus: 'Active',
    description: 'Federal capital nexus, Ministry of Defense headquarters, and central highland redoubt.',
  },
  {
    id: 'city-saopaulo',
    name: 'São Paulo',
    country: 'Brazil',
    countryCode: 'BR',
    flagUrl: 'https://flagcdn.com/w80/br.png',
    lat: -23.5505,
    lng: -46.6333,
    population: '12.3 Million (22M Metro)',
    economicOutput: '$720 Billion',
    militaryReadiness: 'Southeast Industrial Security',
    defenseStatus: 'Fortified',
    description: 'Financial hub of South America and primary industrial conglomerate headquarters.',
  },

  // Canada
  {
    id: 'city-ottawa',
    name: 'Ottawa',
    country: 'Canada',
    countryCode: 'CA',
    flagUrl: 'https://flagcdn.com/w80/ca.png',
    lat: 45.4215,
    lng: -75.6972,
    population: '1.0 Million',
    economicOutput: '$90 Billion',
    militaryReadiness: 'NORAD Integrated',
    defenseStatus: 'Active',
    description: 'National Defense Headquarters and joint Arctic air surveillance coordination center.',
  },
  {
    id: 'city-toronto',
    name: 'Toronto',
    country: 'Canada',
    countryCode: 'CA',
    flagUrl: 'https://flagcdn.com/w80/ca.png',
    lat: 43.6532,
    lng: -79.3832,
    population: '3.0 Million (6.4M Metro)',
    economicOutput: '$450 Billion',
    militaryReadiness: 'Great Lakes Shield',
    defenseStatus: 'Defended',
    description: 'Dominant Canadian financial hub, Bay Street exchange, and advanced AI research center.',
  },

  // Australia
  {
    id: 'city-canberra',
    name: 'Canberra',
    country: 'Australia',
    countryCode: 'AU',
    flagUrl: 'https://flagcdn.com/w80/au.png',
    lat: -35.2809,
    lng: 149.13,
    population: '460,000',
    economicOutput: '$45 Billion',
    militaryReadiness: 'Russell Offices HQ',
    defenseStatus: 'Active',
    description: 'Joint Operations Command and Australian Defence Force headquarters.',
  },
  {
    id: 'city-sydney',
    name: 'Sydney',
    country: 'Australia',
    countryCode: 'AU',
    flagUrl: 'https://flagcdn.com/w80/au.png',
    lat: -33.8688,
    lng: 151.2093,
    population: '5.3 Million',
    economicOutput: '$380 Billion',
    militaryReadiness: 'Fleet Base East',
    defenseStatus: 'Fortified',
    description: 'Financial capital of the South Pacific and Royal Australian Navy naval hub.',
  },

  // Italy
  {
    id: 'city-rome',
    name: 'Rome',
    country: 'Italy',
    countryCode: 'IT',
    flagUrl: 'https://flagcdn.com/w80/it.png',
    lat: 41.9028,
    lng: 12.4964,
    population: '2.8 Million',
    economicOutput: '$220 Billion',
    militaryReadiness: 'Stato Maggiore Command',
    defenseStatus: 'Defended',
    description: 'Historic sovereign capital, military defense staff, and Mediterranean diplomatic nexus.',
  },

  // Spain
  {
    id: 'city-madrid',
    name: 'Madrid',
    country: 'Spain',
    countryCode: 'ES',
    flagUrl: 'https://flagcdn.com/w80/es.png',
    lat: 40.4168,
    lng: -3.7038,
    population: '3.3 Million (6.7M Metro)',
    economicOutput: '$310 Billion',
    militaryReadiness: 'Iberian Core Defense',
    defenseStatus: 'Active',
    description: 'Strategic center of the Iberian peninsula and joint operational command bunker.',
  },

  // Ukraine
  {
    id: 'city-kyiv',
    name: 'Kyiv',
    country: 'Ukraine',
    countryCode: 'UA',
    flagUrl: 'https://flagcdn.com/w80/ua.png',
    lat: 50.4501,
    lng: 30.5234,
    population: '2.9 Million',
    economicOutput: '$75 Billion',
    militaryReadiness: 'Combat Hardened Tier 1',
    defenseStatus: 'Fortified',
    description: 'Hero fortress city and strategic high-command operational bunker network.',
  },

  // Poland
  {
    id: 'city-warsaw',
    name: 'Warsaw',
    country: 'Poland',
    countryCode: 'PL',
    flagUrl: 'https://flagcdn.com/w80/pl.png',
    lat: 52.2297,
    lng: 21.0122,
    population: '1.9 Million',
    economicOutput: '$140 Billion',
    militaryReadiness: 'Eastern Flank Vanguard',
    defenseStatus: 'Fortified',
    description: 'Eastern NATO vanguard headquarters and military logistics bridgehead.',
  },

  // Turkey
  {
    id: 'city-ankara',
    name: 'Ankara',
    country: 'Turkey',
    countryCode: 'TR',
    flagUrl: 'https://flagcdn.com/w80/tr.png',
    lat: 39.9334,
    lng: 32.8597,
    population: '5.8 Million',
    economicOutput: '$180 Billion',
    militaryReadiness: 'General Staff Citadel',
    defenseStatus: 'Fortified',
    description: 'Anatolian plateau defense citadel and sovereign defense industries coordination hub.',
  },

  // Israel
  {
    id: 'city-telaviv',
    name: 'Tel Aviv',
    country: 'Israel',
    countryCode: 'IL',
    flagUrl: 'https://flagcdn.com/w80/il.png',
    lat: 32.0853,
    lng: 34.7818,
    population: '470,000 (4.2M Metro)',
    economicOutput: '$260 Billion',
    militaryReadiness: 'Iron Dome Tier 1',
    defenseStatus: 'Fortified',
    description: 'High-tech Silicon Wadi center and Kirya military defense headquarters.',
  },

  // Mexico
  {
    id: 'city-mexicocity',
    name: 'Mexico City',
    country: 'Mexico',
    countryCode: 'MX',
    flagUrl: 'https://flagcdn.com/w80/mx.png',
    lat: 19.4326,
    lng: -99.1332,
    population: '9.2 Million (22M Metro)',
    economicOutput: '$490 Billion',
    militaryReadiness: 'SEDENA HQ Guard',
    defenseStatus: 'Active',
    description: 'Mesoamerican political and financial metropolis guarded by National Defense staff.',
  },

  // South Africa
  {
    id: 'city-pretoria',
    name: 'Pretoria',
    country: 'South Africa',
    countryCode: 'ZA',
    flagUrl: 'https://flagcdn.com/w80/za.png',
    lat: -25.7479,
    lng: 28.2293,
    population: '2.5 Million',
    economicOutput: '$95 Billion',
    militaryReadiness: 'SANDF Command',
    defenseStatus: 'Active',
    description: 'Administrative executive capital and Department of Defence strategic headquarters.',
  },

  // Indonesia
  {
    id: 'city-jakarta',
    name: 'Jakarta',
    country: 'Indonesia',
    countryCode: 'ID',
    flagUrl: 'https://flagcdn.com/w80/id.png',
    lat: -6.2088,
    lng: 106.8456,
    population: '10.5 Million (34M Metro)',
    economicOutput: '$380 Billion',
    militaryReadiness: 'Archipelago Shield',
    defenseStatus: 'Active',
    description: 'ASEAN diplomatic capital commanding Malacca and Sunda maritime straits.',
  },
];
