export interface CountryProfile {
  code: string;
  name: string;
  flagUrl: string;
  worldId: string;
  nationId: string;
  rankTitle: string;
  rankBadge: string;
  rankTier: string;
  militaryBudget: string;
  activePersonnel: string;
}

export const COUNTRY_PROFILES: Record<string, CountryProfile> = {
  US: {
    code: 'US',
    name: 'United States',
    flagUrl: 'https://flagcdn.com/w80/us.png',
    worldId: 'WID-001-ALPHA',
    nationId: 'US-DEF-88210-CENTCOM',
    rankTitle: 'Supreme Allied Commander',
    rankBadge: '⭐⭐⭐⭐⭐',
    rankTier: 'Tier 1 Global Superpower',
    militaryBudget: '$886 Billion',
    activePersonnel: '1,390,000',
  },
  GB: {
    code: 'GB',
    name: 'United Kingdom',
    flagUrl: 'https://flagcdn.com/w80/gb.png',
    worldId: 'WID-002-BRAVO',
    nationId: 'UK-MOD-44102-WHITEHALL',
    rankTitle: 'Field Marshal',
    rankBadge: '⭐⭐⭐⭐',
    rankTier: 'Tier 1 Strategic Ally',
    militaryBudget: '$72 Billion',
    activePersonnel: '148,500',
  },
  FR: {
    code: 'FR',
    name: 'France',
    flagUrl: 'https://flagcdn.com/w80/fr.png',
    worldId: 'WID-003-CHARLIE',
    nationId: 'FR-ARM-33910-HEXAGONE',
    rankTitle: 'Général d’Armée',
    rankBadge: '⭐⭐⭐⭐⭐',
    rankTier: 'Tier 1 Nuclear Power',
    militaryBudget: '$54 Billion',
    activePersonnel: '205,000',
  },
  DE: {
    code: 'DE',
    name: 'Germany',
    flagUrl: 'https://flagcdn.com/w80/de.png',
    worldId: 'WID-004-DELTA',
    nationId: 'DE-BW-49110-BERLIN',
    rankTitle: 'Generalinspekteur',
    rankBadge: '⭐⭐⭐⭐',
    rankTier: 'Tier 1 European Shield',
    militaryBudget: '$67 Billion',
    activePersonnel: '183,000',
  },
  JP: {
    code: 'JP',
    name: 'Japan',
    flagUrl: 'https://flagcdn.com/w80/jp.png',
    worldId: 'WID-005-ECHO',
    nationId: 'JP-JSDF-81093-TOKYO',
    rankTitle: 'General of Joint Staff',
    rankBadge: '⭐⭐⭐⭐',
    rankTier: 'Tier 1 Pacific Guardian',
    militaryBudget: '$55 Billion',
    activePersonnel: '247,000',
  },
  CN: {
    code: 'CN',
    name: 'China',
    flagUrl: 'https://flagcdn.com/w80/cn.png',
    worldId: 'WID-006-FOXTROT',
    nationId: 'CN-PLA-86001-BEIJING',
    rankTitle: 'Grand Marshal',
    rankBadge: '⭐⭐⭐⭐⭐',
    rankTier: 'Tier 1 Eastern Giant',
    militaryBudget: '$296 Billion',
    activePersonnel: '2,035,000',
  },
  RU: {
    code: 'RU',
    name: 'Russia',
    flagUrl: 'https://flagcdn.com/w80/ru.png',
    worldId: 'WID-007-GOLF',
    nationId: 'RU-MO-70014-MOSCOW',
    rankTitle: 'Marshal of the Federation',
    rankBadge: '⭐⭐⭐⭐⭐',
    rankTier: 'Tier 1 Eurasian Arsenal',
    militaryBudget: '$109 Billion',
    activePersonnel: '1,150,000',
  },
  IN: {
    code: 'IN',
    name: 'India',
    flagUrl: 'https://flagcdn.com/w80/in.png',
    worldId: 'WID-008-HOTEL',
    nationId: 'IN-MOD-91040-DELHI',
    rankTitle: 'Chief of Defence Staff',
    rankBadge: '⭐⭐⭐⭐⭐',
    rankTier: 'Tier 1 Subcontinent Fortress',
    militaryBudget: '$83 Billion',
    activePersonnel: '1,450,000',
  },
  BR: {
    code: 'BR',
    name: 'Brazil',
    flagUrl: 'https://flagcdn.com/w80/br.png',
    worldId: 'WID-009-INDIA',
    nationId: 'BR-DEF-55100-BRASILIA',
    rankTitle: 'Marechal do Exército',
    rankBadge: '⭐⭐⭐⭐',
    rankTier: 'Tier 2 Continental Sentinel',
    militaryBudget: '$23 Billion',
    activePersonnel: '360,000',
  },
  CA: {
    code: 'CA',
    name: 'Canada',
    flagUrl: 'https://flagcdn.com/w80/ca.png',
    worldId: 'WID-010-JULIET',
    nationId: 'CA-DND-10020-OTTAWA',
    rankTitle: 'Chief of the Defence Staff',
    rankBadge: '⭐⭐⭐⭐',
    rankTier: 'Tier 2 Arctic Watch',
    militaryBudget: '$27 Billion',
    activePersonnel: '68,000',
  },
  AU: {
    code: 'AU',
    name: 'Australia',
    flagUrl: 'https://flagcdn.com/w80/au.png',
    worldId: 'WID-011-KILO',
    nationId: 'AU-ADF-61001-CANBERRA',
    rankTitle: 'Air Chief Marshal',
    rankBadge: '⭐⭐⭐⭐',
    rankTier: 'Tier 2 Southern Vanguard',
    militaryBudget: '$32 Billion',
    activePersonnel: '60,000',
  },
  KR: {
    code: 'KR',
    name: 'South Korea',
    flagUrl: 'https://flagcdn.com/w80/kr.png',
    worldId: 'WID-012-LIMA',
    nationId: 'KR-ROK-82100-SEOUL',
    rankTitle: 'General of the ROK Armed Forces',
    rankBadge: '⭐⭐⭐⭐⭐',
    rankTier: 'Tier 1 Peninsular Fortress',
    militaryBudget: '$48 Billion',
    activePersonnel: '555,000',
  },
  IT: {
    code: 'IT',
    name: 'Italy',
    flagUrl: 'https://flagcdn.com/w80/it.png',
    worldId: 'WID-013-MIKE',
    nationId: 'IT-SMD-39001-ROMA',
    rankTitle: 'Generale di Corpo d’Armata',
    rankBadge: '⭐⭐⭐⭐',
    rankTier: 'Tier 2 Mediterranean Bastion',
    militaryBudget: '$33 Billion',
    activePersonnel: '165,000',
  },
  NG: {
    code: 'NG',
    name: 'Nigeria',
    flagUrl: 'https://flagcdn.com/w80/ng.png',
    worldId: 'WID-014-NOVEMBER',
    nationId: 'NG-DHQ-23401-ABUJA',
    rankTitle: 'Chief of Defence Staff',
    rankBadge: '⭐⭐⭐⭐',
    rankTier: 'Tier 2 African Sovereign Command',
    militaryBudget: '$4.2 Billion',
    activePersonnel: '223,000',
  },
  ZA: {
    code: 'ZA',
    name: 'South Africa',
    flagUrl: 'https://flagcdn.com/w80/za.png',
    worldId: 'WID-015-OSCAR',
    nationId: 'ZA-SANDF-27001-PRETORIA',
    rankTitle: 'General of SANDF',
    rankBadge: '⭐⭐⭐⭐',
    rankTier: 'Tier 2 Cape Vanguard',
    militaryBudget: '$3.5 Billion',
    activePersonnel: '74,000',
  },
  EG: {
    code: 'EG',
    name: 'Egypt',
    flagUrl: 'https://flagcdn.com/w80/eg.png',
    worldId: 'WID-016-PAPA',
    nationId: 'EG-MOD-20010-CAIRO',
    rankTitle: 'Field Marshal',
    rankBadge: '⭐⭐⭐⭐⭐',
    rankTier: 'Tier 1 Suez Guardian',
    militaryBudget: '$9.4 Billion',
    activePersonnel: '440,000',
  },
  SA: {
    code: 'SA',
    name: 'Saudi Arabia',
    flagUrl: 'https://flagcdn.com/w80/sa.png',
    worldId: 'WID-017-QUEBEC',
    nationId: 'SA-MOD-96601-RIYADH',
    rankTitle: 'General Staff Commander',
    rankBadge: '⭐⭐⭐⭐',
    rankTier: 'Tier 1 Gulf Bulwark',
    militaryBudget: '$69 Billion',
    activePersonnel: '257,000',
  },
  IL: {
    code: 'IL',
    name: 'Israel',
    flagUrl: 'https://flagcdn.com/w80/il.png',
    worldId: 'WID-018-ROMEO',
    nationId: 'IL-IDF-97201-TELAVIV',
    rankTitle: 'Ramatkal (Chief of Staff)',
    rankBadge: '⭐⭐⭐⭐⭐',
    rankTier: 'Tier 1 Precision Defense',
    militaryBudget: '$24 Billion',
    activePersonnel: '170,000',
  },
  TR: {
    code: 'TR',
    name: 'Turkey',
    flagUrl: 'https://flagcdn.com/w80/tr.png',
    worldId: 'WID-019-SIERRA',
    nationId: 'TR-TSK-90001-ANKARA',
    rankTitle: 'Orgeneral (General of the Army)',
    rankBadge: '⭐⭐⭐⭐⭐',
    rankTier: 'Tier 1 Anatolian Crossroad',
    militaryBudget: '$25 Billion',
    activePersonnel: '425,000',
  },
  UA: {
    code: 'UA',
    name: 'Ukraine',
    flagUrl: 'https://flagcdn.com/w80/ua.png',
    worldId: 'WID-020-TANGO',
    nationId: 'UA-AFU-38001-KYIV',
    rankTitle: 'Commander-in-Chief',
    rankBadge: '⭐⭐⭐⭐⭐',
    rankTier: 'Tier 1 Battle-Tested Frontline',
    militaryBudget: '$40 Billion',
    activePersonnel: '700,000',
  },
};
